#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-Business-ISBN
Version  : 3.008
Release  : 26
URL      : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-3.008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-3.008.tar.gz
Summary  : 'work with International Standard Book Numbers'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Business-ISBN-perl = %{version}-%{release}
Requires: perl(Business::ISBN::Data)
BuildRequires : buildreq-cpan
BuildRequires : perl(Business::ISBN::Data)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
See the tests in the t/ directory for examples until I add some more.

%package dev
Summary: dev components for the perl-Business-ISBN package.
Group: Development
Provides: perl-Business-ISBN-devel = %{version}-%{release}
Requires: perl-Business-ISBN = %{version}-%{release}

%description dev
dev components for the perl-Business-ISBN package.


%package perl
Summary: perl components for the perl-Business-ISBN package.
Group: Default
Requires: perl-Business-ISBN = %{version}-%{release}

%description perl
perl components for the perl-Business-ISBN package.


%prep
%setup -q -n Business-ISBN-3.008
cd %{_builddir}/Business-ISBN-3.008

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Business::ISBN.3
/usr/share/man/man3/Business::ISBN10.3
/usr/share/man/man3/Business::ISBN13.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
